[project]
id = "edtoxcmzdsskklldhzsfv"

[db]
port = 5432
shadow_port = 5433
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
